import ContenidoBlog from "../components/miblog/ContenidoBlog"
export const publicaciones=[
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937216/sitioweb/Los_beneficios_de_usar_Shopify_para_crear_tu_tienda_en_l%C3%ADnea_xj2mub.jpg",
    categoria:"Tienda virtual shopify",
titulo:"Los beneficios de usar Shopify para crear tu tienda en línea",
url:'benificios-crear-tienda-shopify',
parrafo:<ContenidoBlog content='contenido_01.md'/>,
description_seo:"¿Quieres abrir una tienda en línea y no sabes por dónde empezar? Descubre en nuestro artículo los beneficios de usar Shopify para crear tu tienda en línea. Aprende cómo esta plataforma de comercio electrónico puede ayudarte a vender tus productos en línea de manera rápida y fácil, con características de diseño y marketing digital incluidas. Empieza a vender en línea hoy mismo con Shopify."},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937215/sitioweb/C%C3%B3mo_elegir_el_tema_adecuado_para_tu_tienda_Shopify_mfaper.jpg",
categoria:"Tienda virtual shopify",
titulo:"Cómo elegir el tema adecuado para tu tienda Shopify",
url:'elegir-tema-shopify',
parrafo:<ContenidoBlog content='contenido_02.md'/>,
description_seo:"La elección del tema adecuado para tu tienda Shopify puede marcar la diferencia en tu éxito en línea. Descubre en nuestro artículo cómo elegir el tema perfecto para tu tienda, con consejos sobre diseño, funcionalidad y optimización para motores de búsqueda. Aprende a personalizar tu tienda en línea con las mejores prácticas de diseño y marketing digital. Empieza a mejorar la experiencia de tus clientes en línea hoy mismo."},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937417/sitioweb/Pasos_para_optimizar_la_velocidad_de_carga_de_tu_tienda_Shopify_fdxzwg.jpg",
categoria:"Optimización",
titulo:"Pasos para optimizar la velocidad de carga de tu tienda Shopify",
url:'optimizar-tienda-shopify',
parrafo:<ContenidoBlog content='contenido_03.md'/>,
description_seo:"La velocidad de carga de tu tienda Shopify es crucial para mantener a tus clientes satisfechos y mejorar tu posicionamiento en línea. Descubre en nuestro artículo los pasos para optimizar la velocidad de carga de tu tienda Shopify, desde la elección del tema hasta la optimización de imágenes y el uso de aplicaciones. Aprende a mejorar la velocidad de tu tienda y a brindar una experiencia de usuario más rápida y eficiente."},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937215/sitioweb/C%C3%B3mo_integrar_tu_tienda_Shopify_con_redes_sociales_y_otras_plataformas_de_venta_pihgyf.jpg",
categoria:"Tienda virtual shopify",
titulo:"Cómo integrar tu tienda Shopify con redes sociales y otras plataformas de venta",
url:'intergrar-redes-sociales-otras-plataformas',
parrafo:<ContenidoBlog content='contenido_04.md'/>,
description_seo:"La integración de tu tienda Shopify con redes sociales y otras plataformas de venta puede ayudarte a llegar a más clientes y aumentar tus ventas en línea. Descubre en nuestro artículo cómo integrar tu tienda con Facebook, Instagram, Amazon y otras plataformas de venta, con consejos prácticos sobre herramientas y estrategias de marketing digital. Aprende a expandir tu alcance en línea y a llegar a nuevos clientes en todas partes."},
]
export const publicaciones_populares=[
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937216/sitioweb/5_aplicaciones_de_Shopify_que_no_te_puedes_perder_para_tu_tienda_virtual_vq6zzb.jpg",
    categoria:"Tienda virtual shopify",
    titulo:"5 aplicaciones de Shopify que no te puedes perder para tu tienda virtual",
    url:'5-aplicaciones-shopify',
    parrafo:<ContenidoBlog content='contenido_05.md'/>,
    description_seo:"Descubre en nuestro artículo las 5 aplicaciones de Shopify que no te puedes perder para mejorar la funcionalidad y el rendimiento de tu tienda virtual. Desde herramientas de marketing digital hasta aplicaciones de automatización de tareas, aprende cómo estas aplicaciones pueden ayudarte a optimizar tu tienda y aumentar tus ventas en línea. Empieza a mejorar tu tienda virtual hoy mismo con estas aplicaciones imprescindibles."},
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937216/sitioweb/5_razones_por_las_que_tu_negocio_necesita_una_tienda_virtual_en_Shopify_elugcl.jpg",
    categoria:"Tienda virtual shopify",
    titulo:"5 razones por las que tu negocio necesita una tienda virtual en Shopify",
    url:'5-razones-por-las-que-tu-negocio-necesita-una-tienda-virtual-en-Shopify',
    parrafo:<ContenidoBlog content='contenido_06.md'/>,
    description_seo:"Descubre en nuestro artículo las 5 razones por las que tu negocio necesita una tienda virtual en Shopify. Desde la expansión de tu alcance en línea hasta la facilidad de uso y la flexibilidad de diseño, aprende cómo una tienda virtual en Shopify puede ayudarte a aumentar tus ventas en línea y a mejorar la experiencia de tus clientes. No pierdas la oportunidad de llevar tu negocio al siguiente nivel con una tienda virtual en Shopify."}, 
]